server:
  port: 8088
  servlet:
    context-path: /eilen
spring:
  datasource:
    url: jdbc:mysql://59.110.225.54/eilen
    username: eilen
    password: 5110
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    suffix: .html
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    mode: HTML5
  security:
    user:
      name: user
      password: user
logging:
  level:
    com.start.springbootstart.repository: debug