server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://59.110.225.54:3306/eilen
    username: eilen
    password: 5110
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
logging:
  level:
    com.mybatis.mybatis.mapper: debug